### 1. Import the numpy package under the name np

hint: import … as

In [4]:
# YOUR CODE HERE
import numpy as np

### 2. Print the numpy version and the configuration

hint: np.__version__, np.show_config

In [6]:
# YOUR CODE HERE
print(np.show_config)

<function show at 0x7fda15064950>


### 3. Create a null vector of size 10

hint: np.zeros

In [8]:
# YOUR CODE HERE
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1

hint: array[4]

In [9]:
# YOUR CODE HERE
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49

hint: arange

In [10]:
# YOUR CODE HERE
x=np.arange(10,49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

### 6. Reverse a vector (first element becomes last)

hint: array[::-1]

In [11]:
# YOUR CODE HERE
x1=x[::-1]
print(x1)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 7. Find indices of non-zero elements from [1,2,0,0,4,0]

hint: np.nonzero

In [22]:
# YOUR CODE HERE

arr=np.array([1,2,0,0,4,0])
arr
y=arr[np.nonzero(arr)]
y


array([1, 2, 4])

### 8. Create a 3x3 identity matrix

hint: np.eye

In [23]:
# YOUR CODE HERE

f=np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 9. Create a 3x3x3 array with random values

hint: np.random.random

In [32]:
# YOUR CODE HERE
z=np.random.random(size=(3,3,3))
z

array([[[0.25069   , 0.38543825, 0.07813835],
        [0.20284191, 0.51262868, 0.63493971],
        [0.01186993, 0.69502755, 0.82116745]],

       [[0.44126993, 0.4468408 , 0.12701197],
        [0.90568468, 0.09969289, 0.12601075],
        [0.67671541, 0.73486116, 0.70210702]],

       [[0.38960119, 0.43591413, 0.34782099],
        [0.85534937, 0.4714335 , 0.79641372],
        [0.94725698, 0.05348384, 0.85693908]]])

### 10. Create a 10x10 array with random values and find the minimum and maximum values

hint: min, max

In [42]:
# YOUR CODE HERE

t=np.random.randint(20,size=(10,10))
print(t)
print(t.min())
print(t.max())


[[ 5 17 14  2  8 18  4  5  8  6]
 [17  1  6  5  4 13 13 19 16  6]
 [16  1 17  1  9 16  8  5 12 16]
 [ 4 18  5 19 13 16 15  7 12  6]
 [10  9  0  7 13  8 18  4 14  9]
 [ 6  3 15  7 15 13 10  4 18 18]
 [ 7 17 14  4  3  6 12 13 11 15]
 [ 5 12  3 19  3 16 16  7 18  2]
 [ 1 10 18  0  7 19 14  0  1 18]
 [ 7 17  0 15  9 16  9  1  0  6]]
0
19


### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

hint: np.diag

In [57]:
# YOUR CODE HERE'
f=np.random.randint(20,size=(5,5))
print(f)
g=np.diag([1,2,3,4,5],-1)
print(g)

[[16 15 16  2 17]
 [ 9  2  0  8 11]
 [16 13  6  3  5]
 [11 19 16 16 16]
 [ 1  8 11 10  0]]
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


### 12. Matrix multiplication for 1-D array. 

To multiply the matrix a and b,
hint: np.dot

In [59]:
import numpy as np

a = np.array([9, 5, 7, 4])
b = np.array([9, 5, 4, 3])

# YOUR CODE HERE
z=np.dot(a,b)
print(z)

146


## 13. Matrix multiplication for 2-D array.

To multiply the matrix a and b, 
hint: np.dot

In [60]:
a = np.array([[1, 0],
             [0, 1]])

b = np.array([[4, 1],
              [2, 2]])


# YOUR CODE HERE
z=np.dot(a,b)
print(z)

[[4 1]
 [2 2]]


### 14. Transpose the given array [[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]]
Hint :: np.transpose()

In [61]:
# YOUR CODE HERE

arr = [[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]]
tarr=np.transpose(arr)
tarr

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

###15. Inverse the given array [[3,4],[5,6]]
Hint:: np.linalg.inv()

In [62]:
# YOUR CODE HERE
arr =  [[3,4],[5,6]]
iarr=np.linalg.inv(arr)
iarr

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

###16. Concatenate two numpy arrays by columnwise  by specifying axis 1
Hint::np.concatenate()

In [64]:
c =np.array([[1,2],[3,4]])
d =np.array([[5,6],[7,8]])

# YOUR CODE HERE
con=np.concatenate((c,d),axis=1)
con

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

###17. For Given a Multidimensional array print second and third column


In [67]:
a = np.array([[2, 4, 6, 8, 10], 
              [3, 6, 9, 12, 15], 
              [4, 8, 12, 16, 20]]) 

# YOUR CODE HERE

print(a[:,1:3])

[[ 4  6]
 [ 6  9]
 [ 8 12]]


###18. For Given Multidimensional array:
#### 1.Calculate mean row wise by specifying axis = 0 and column wise by specifying axis =1
#### 2. What is the average value of array

In [68]:
import numpy as np 
# 2D array  
array = np.array([[2, 4, 6, 8, 10], 
              [3, 6, 9, 12, 15], 
              [4, 8, 12, 16, 20]]) 


#YOUR CODE HERE
print(np.mean(array,axis=1))
print(np.mean(array,axis=0))

[ 6.  9. 12.]
[ 3.  6.  9. 12. 15.]


###19. Create an array of all the even numbers from 30 to 70.

In [73]:
#YOUR CODE HERE
arr=np.arange(30,71,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### 20. For the given array, get the slice of the first row and print them.

In [ ]:
import numpy as np

In [74]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])


#YOUR CODE HERE
print(a3[:,0:1])

[[[10 11 12]]

 [[20 21 22]]

 [[30 31 32]]]
